CREATE TABLE IF NOT EXISTS guestbook_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 60),
    note text NOT NULL CHECK (char_length(note) BETWEEN 1 AND 280),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_guestbook_entries_created_at_not_future CHECK (created_at <= now() + interval '1 minute')
);

CREATE INDEX IF NOT EXISTS idx_guestbook_entries_created_at_id ON guestbook_entries (created_at DESC, id DESC);
